// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Data;

namespace Portal.Migrations
{
    [DbContext(typeof(AcademyContext))]
    [Migration("20260825184900_addCompletedSubject")]
    partial class addCompletedSubject
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.Models.CompletedSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompletedSubjects");
                });

            modelBuilder.Entity("Portal.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arch")
                        .HasColumnType("bit");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Portal.Models.Elective.El_Stud_Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ElectiveID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElectiveID");

                    b.ToTable("El_Stud_Links");
                });

            modelBuilder.Entity("Portal.Models.Elective.Elective", b =>
                {
                    b.Property<int>("ElectiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElectiveID");

                    b.ToTable("Electives");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveLesson", b =>
                {
                    b.Property<int>("ElectiveLessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("ElectiveThemeID")
                        .HasColumnType("int");

                    b.Property<int>("ElectiveTypeID")
                        .HasColumnType("int");

                    b.Property<int>("FlagF")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElectiveLessonID");

                    b.HasIndex("ElectiveThemeID");

                    b.HasIndex("ElectiveTypeID");

                    b.HasIndex("Date", "FlagF");

                    b.ToTable("ElectiveLessons");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveMark", b =>
                {
                    b.Property<int>("ElectiveMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElectiveLessonID")
                        .HasColumnType("int");

                    b.Property<int>("FlagF")
                        .HasColumnType("int");

                    b.Property<string>("HistoryOfMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureOfTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElectiveMarkID");

                    b.HasIndex("ElectiveLessonID");

                    b.HasIndex("Date", "FlagF");

                    b.ToTable("ElectiveMarks");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveTheme", b =>
                {
                    b.Property<int>("ElectiveThemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Archive")
                        .HasColumnType("bit");

                    b.Property<int>("ElectiveID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElectiveThemeID");

                    b.HasIndex("ElectiveID");

                    b.ToTable("ElectiveThemes");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveType", b =>
                {
                    b.Property<int>("ElectiveTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Archive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ElectiveTypeID");

                    b.ToTable("ElectiveTypes");
                });

            modelBuilder.Entity("Portal.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Log")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teacher")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Portal.Models.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEnter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExit")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityID")
                        .HasColumnType("int");

                    b.HasKey("GroupID");

                    b.HasIndex("DateExit");

                    b.HasIndex("SpecialityID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Portal.Models.GroupArhive", b =>
                {
                    b.Property<int>("GroupArhiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEnter")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExit")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityID")
                        .HasColumnType("int");

                    b.HasKey("GroupArhiveID");

                    b.HasIndex("SpecialityID");

                    b.ToTable("GroupArhives");
                });

            modelBuilder.Entity("Portal.Models.Institute", b =>
                {
                    b.Property<int>("InstituteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arch")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstituteID");

                    b.ToTable("Institutes");
                });

            modelBuilder.Entity("Portal.Models.Journal", b =>
                {
                    b.Property<int>("JournalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("JournalID");

                    b.HasIndex("SubjectID");

                    b.HasIndex("GroupID", "SubjectID");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Portal.Models.JournalArhive", b =>
                {
                    b.Property<int>("JournalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupArhiveID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.HasKey("JournalID");

                    b.HasIndex("GroupArhiveID");

                    b.HasIndex("SubjectID");

                    b.ToTable("JournalArhives");
                });

            modelBuilder.Entity("Portal.Models.Lesson", b =>
                {
                    b.Property<int>("LessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlagF")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("ThemeID")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.HasKey("LessonID");

                    b.HasIndex("GroupID");

                    b.HasIndex("ThemeID");

                    b.HasIndex("TypeOfExerciseID");

                    b.HasIndex("SubjectID", "Date", "FlagF");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Portal.Models.LessonArhive", b =>
                {
                    b.Property<int>("LessonArhiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlagF")
                        .HasColumnType("int");

                    b.Property<int>("GroupArhiveID")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("ThemeID")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.HasKey("LessonArhiveID");

                    b.HasIndex("GroupArhiveID");

                    b.HasIndex("ThemeID");

                    b.HasIndex("TypeOfExerciseID");

                    b.HasIndex("SubjectID", "Date", "FlagF");

                    b.ToTable("LessonArhives");
                });

            modelBuilder.Entity("Portal.Models.Mark", b =>
                {
                    b.Property<int>("MarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChangeCounter")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("FlagF")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("HistoryOfMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("SignatureOfTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("ThemeID")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkID");

                    b.HasIndex("StudentID");

                    b.HasIndex("ThemeID");

                    b.HasIndex("Date", "FlagF", "SubjectID", "GroupID");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("Portal.Models.MarkArhive", b =>
                {
                    b.Property<int>("MarkArhiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("FlagF")
                        .HasColumnType("int");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("HistoryOfMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<int>("LessonID")
                        .HasColumnType("int");

                    b.Property<string>("SignatureOfTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityID")
                        .HasColumnType("int");

                    b.Property<int>("StudentArhiveID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<int>("ThemeID")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarkArhiveID");

                    b.HasIndex("StudentArhiveID");

                    b.HasIndex("ThemeID");

                    b.HasIndex("Date", "FlagF", "SubjectID", "GroupID");

                    b.ToTable("MarkArhives");
                });

            modelBuilder.Entity("Portal.Models.Speciality", b =>
                {
                    b.Property<int>("SpecialityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arch")
                        .HasColumnType("bit");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeOFStudy")
                        .HasColumnType("int");

                    b.HasKey("SpecialityID");

                    b.HasIndex("InstituteID");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("Portal.Models.StatementLesson", b =>
                {
                    b.Property<int>("StatementLessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.HasKey("StatementLessonID");

                    b.HasIndex("GroupID");

                    b.HasIndex("TypeOfExerciseID");

                    b.ToTable("StatementLessons");
                });

            modelBuilder.Entity("Portal.Models.StatementLessonArhive", b =>
                {
                    b.Property<int>("StatementLessonArhiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupArhiveID")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.HasKey("StatementLessonArhiveID");

                    b.HasIndex("GroupArhiveID");

                    b.HasIndex("TypeOfExerciseID");

                    b.ToTable("StatementLessonArhives");
                });

            modelBuilder.Entity("Portal.Models.StatementMark", b =>
                {
                    b.Property<int>("StatementMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("HistoryOfMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("SignatureOfTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityID")
                        .HasColumnType("int");

                    b.Property<int>("StatementLessonID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatementMarkID");

                    b.HasIndex("StudentID");

                    b.ToTable("StatementMarks");
                });

            modelBuilder.Entity("Portal.Models.StatementMarkArhive", b =>
                {
                    b.Property<int>("StatementMarkArhiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("HistoryOfMark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("SignatureOfTeacher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialityID")
                        .HasColumnType("int");

                    b.Property<int>("StatementLessonID")
                        .HasColumnType("int");

                    b.Property<int>("StudentArhiveID")
                        .HasColumnType("int");

                    b.Property<int>("TypeOfExerciseID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatementMarkArhiveID");

                    b.HasIndex("StudentArhiveID");

                    b.ToTable("StatementMarkArhives");
                });

            modelBuilder.Entity("Portal.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.HasIndex("GroupID");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Portal.Models.StudentArhive", b =>
                {
                    b.Property<int>("StudentArhiveID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupArhiveID")
                        .HasColumnType("int");

                    b.Property<int>("InstituteID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentArhiveID");

                    b.HasIndex("GroupArhiveID");

                    b.ToTable("StudentArhives");
                });

            modelBuilder.Entity("Portal.Models.Sub_SpecLink", b =>
                {
                    b.Property<int>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SpecialityID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkID");

                    b.ToTable("Sub_SpecLinks");
                });

            modelBuilder.Entity("Portal.Models.Subject", b =>
                {
                    b.Property<int>("SubjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arch")
                        .HasColumnType("bit");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Portal.Models.Teacher", b =>
                {
                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FamilyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherID");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Portal.Models.TeacherNoPC", b =>
                {
                    b.Property<int>("TeacherNoPCID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeacherNoPCID");

                    b.ToTable("TeacherNoPCs");
                });

            modelBuilder.Entity("Portal.Models.Theme", b =>
                {
                    b.Property<int>("ThemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arch")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThemeID");

                    b.HasIndex("SubjectID");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("Portal.Models.TypeOfExercise", b =>
                {
                    b.Property<int>("TypeOfExerciseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Arch")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeOfExerciseID");

                    b.ToTable("TypeOfExercise");
                });

            modelBuilder.Entity("Portal.Models.UnsatisfactoryMark", b =>
                {
                    b.Property<int>("UnsatisfactoryMarkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CorrectedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrectedValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupID")
                        .HasColumnType("int");

                    b.Property<int>("MarkID")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UnsatisfactoryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnsatisfactoryValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnsatisfactoryMarkID");

                    b.ToTable("UnsatisfactoryMarks");
                });

            modelBuilder.Entity("Portal.Models.Elective.El_Stud_Link", b =>
                {
                    b.HasOne("Portal.Models.Elective.Elective", "Elective")
                        .WithMany("StudLinks")
                        .HasForeignKey("ElectiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elective");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveLesson", b =>
                {
                    b.HasOne("Portal.Models.Elective.ElectiveTheme", "Theme")
                        .WithMany("Lessons")
                        .HasForeignKey("ElectiveThemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.Elective.ElectiveType", "Type")
                        .WithMany("Lessons")
                        .HasForeignKey("ElectiveTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveMark", b =>
                {
                    b.HasOne("Portal.Models.Elective.ElectiveLesson", "ElectiveLesson")
                        .WithMany("Marks")
                        .HasForeignKey("ElectiveLessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ElectiveLesson");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveTheme", b =>
                {
                    b.HasOne("Portal.Models.Elective.Elective", "Elective")
                        .WithMany("Themes")
                        .HasForeignKey("ElectiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elective");
                });

            modelBuilder.Entity("Portal.Models.Group", b =>
                {
                    b.HasOne("Portal.Models.Speciality", "Speciality")
                        .WithMany("Groups")
                        .HasForeignKey("SpecialityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Portal.Models.GroupArhive", b =>
                {
                    b.HasOne("Portal.Models.Speciality", "Speciality")
                        .WithMany("GroupArhives")
                        .HasForeignKey("SpecialityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("Portal.Models.Journal", b =>
                {
                    b.HasOne("Portal.Models.Group", "Group")
                        .WithMany("Journals")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.Subject", "Subject")
                        .WithMany("Journals")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Portal.Models.JournalArhive", b =>
                {
                    b.HasOne("Portal.Models.GroupArhive", "GroupArhive")
                        .WithMany("Journals")
                        .HasForeignKey("GroupArhiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.Subject", "Subject")
                        .WithMany("JournalArhives")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupArhive");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Portal.Models.Lesson", b =>
                {
                    b.HasOne("Portal.Models.Group", "Group")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.Theme", "Theme")
                        .WithMany("Lessons")
                        .HasForeignKey("ThemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.TypeOfExercise", "TypeOfExercise")
                        .WithMany("Lessons")
                        .HasForeignKey("TypeOfExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Theme");

                    b.Navigation("TypeOfExercise");
                });

            modelBuilder.Entity("Portal.Models.LessonArhive", b =>
                {
                    b.HasOne("Portal.Models.GroupArhive", "GroupArhive")
                        .WithMany("Lessons")
                        .HasForeignKey("GroupArhiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.Theme", "Theme")
                        .WithMany("LessonArhives")
                        .HasForeignKey("ThemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.TypeOfExercise", "TypeOfExercise")
                        .WithMany("LessonArhives")
                        .HasForeignKey("TypeOfExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupArhive");

                    b.Navigation("Theme");

                    b.Navigation("TypeOfExercise");
                });

            modelBuilder.Entity("Portal.Models.Mark", b =>
                {
                    b.HasOne("Portal.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.Theme", "Theme")
                        .WithMany("Marks")
                        .HasForeignKey("ThemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Portal.Models.MarkArhive", b =>
                {
                    b.HasOne("Portal.Models.StudentArhive", "StudentArhive")
                        .WithMany("Marks")
                        .HasForeignKey("StudentArhiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.Theme", "Theme")
                        .WithMany("MarkArhives")
                        .HasForeignKey("ThemeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentArhive");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("Portal.Models.Speciality", b =>
                {
                    b.HasOne("Portal.Models.Institute", "Institute")
                        .WithMany("Specialities")
                        .HasForeignKey("InstituteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("Portal.Models.StatementLesson", b =>
                {
                    b.HasOne("Portal.Models.Group", "Group")
                        .WithMany("StatementLessons")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.TypeOfExercise", "TypeOfExercise")
                        .WithMany("StatementLessons")
                        .HasForeignKey("TypeOfExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("TypeOfExercise");
                });

            modelBuilder.Entity("Portal.Models.StatementLessonArhive", b =>
                {
                    b.HasOne("Portal.Models.GroupArhive", "GroupArhive")
                        .WithMany("StatementLessons")
                        .HasForeignKey("GroupArhiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Portal.Models.TypeOfExercise", "TypeOfExercise")
                        .WithMany("StatementLessonArhives")
                        .HasForeignKey("TypeOfExerciseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupArhive");

                    b.Navigation("TypeOfExercise");
                });

            modelBuilder.Entity("Portal.Models.StatementMark", b =>
                {
                    b.HasOne("Portal.Models.Student", "Student")
                        .WithMany("StatementMarks")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Portal.Models.StatementMarkArhive", b =>
                {
                    b.HasOne("Portal.Models.StudentArhive", "StudentArhive")
                        .WithMany("StatementMarks")
                        .HasForeignKey("StudentArhiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentArhive");
                });

            modelBuilder.Entity("Portal.Models.Student", b =>
                {
                    b.HasOne("Portal.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Portal.Models.StudentArhive", b =>
                {
                    b.HasOne("Portal.Models.GroupArhive", "GroupArhive")
                        .WithMany("Students")
                        .HasForeignKey("GroupArhiveID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupArhive");
                });

            modelBuilder.Entity("Portal.Models.Subject", b =>
                {
                    b.HasOne("Portal.Models.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Portal.Models.Theme", b =>
                {
                    b.HasOne("Portal.Models.Subject", "Subject")
                        .WithMany("Themes")
                        .HasForeignKey("SubjectID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Portal.Models.Department", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("Portal.Models.Elective.Elective", b =>
                {
                    b.Navigation("StudLinks");

                    b.Navigation("Themes");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveLesson", b =>
                {
                    b.Navigation("Marks");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveTheme", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Portal.Models.Elective.ElectiveType", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("Portal.Models.Group", b =>
                {
                    b.Navigation("Journals");

                    b.Navigation("Lessons");

                    b.Navigation("StatementLessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Portal.Models.GroupArhive", b =>
                {
                    b.Navigation("Journals");

                    b.Navigation("Lessons");

                    b.Navigation("StatementLessons");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Portal.Models.Institute", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("Portal.Models.Speciality", b =>
                {
                    b.Navigation("GroupArhives");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Portal.Models.Student", b =>
                {
                    b.Navigation("Marks");

                    b.Navigation("StatementMarks");
                });

            modelBuilder.Entity("Portal.Models.StudentArhive", b =>
                {
                    b.Navigation("Marks");

                    b.Navigation("StatementMarks");
                });

            modelBuilder.Entity("Portal.Models.Subject", b =>
                {
                    b.Navigation("JournalArhives");

                    b.Navigation("Journals");

                    b.Navigation("Themes");
                });

            modelBuilder.Entity("Portal.Models.Theme", b =>
                {
                    b.Navigation("LessonArhives");

                    b.Navigation("Lessons");

                    b.Navigation("MarkArhives");

                    b.Navigation("Marks");
                });

            modelBuilder.Entity("Portal.Models.TypeOfExercise", b =>
                {
                    b.Navigation("LessonArhives");

                    b.Navigation("Lessons");

                    b.Navigation("StatementLessonArhives");

                    b.Navigation("StatementLessons");
                });
#pragma warning restore 612, 618
        }
    }
}
